blank_issues_enabled: false
issue_template_chooser:
  custom_templates:
    - name: Tracking issue
      about: Use this template for tracking new features.
      template: experiment_issue_template.md
      title: "[Experiment]: "